### ISSUE TITLE
the preprocessed Fundus dataset

### ISSUE THREAD

**Issue by bigfishfour** [MQinghe/MiDSS#2]
Hello, thank you very much for providing such excellent work. Would it be convenient for you to provide the preprocessed Fundus dataset？Thank you very much!

**Comment by MQinghe** [comment]
Thank you for your interest in our work! The Fundus dataset used in our code has not undergone any additional preprocessing. You can download the dataset from the following link: [Fundus Dataset](https://drive.google.com/file/d/1p33nsWQaiZMAgsruDoJLyatoq5XAH-TH/view)，and select the first n (e.g., 20) images in the training set of one domain as the labeled data.

**Comment by bigfishfour** [comment]
thank you very much!
