### ISSUE TITLE
preprocessed Prostate dataset

### ISSUE THREAD

**Issue by bigfishfour** [MQinghe/MiDSS#3]
Hello author, I'm sorry to bother you again. Do you have a preprocessed Prostate dataset？Thank you very much!

**Comment by MQinghe** [comment]
You can download the dataset from the following link: [Prostate Dataset](https://pan.baidu.com/s/1LO2weT01DosfGb3GKLoOvA) with the extraction code: 4no2

**Comment by bigfishfour** [comment]
> You can download the dataset from the following link: [Prostate Dataset](https://pan.baidu.com/s/1LO2weT01DosfGb3GKLoOvA) with the extraction code: 4no2

thank u very much!!!!：）

**Comment by TalibDaryabi** [comment]
@bigfishfour  were you able to manage and downlaod it?
