### ISSUE TITLE
Data preprocessing

### ISSUE THREAD

**Issue by Lingyu110** [MQinghe/MiDSS#5]
I'm very sorry to bother you again. Can you share the M&M preprocessed dataset?

**Comment by MQinghe** [comment]
You can download the dataset from the following link: [M&Ms Dataset](https://pan.baidu.com/s/1EG1RTIHcJmuzApd8_jvL6w 
) with the extraction code: cdbs

**Comment by Yanglingling110** [comment]
Thank you for replying and sharing so timely!
