### ISSUE TITLE
The model weight file corresponding to the article results

### ISSUE THREAD

**Issue by Xi-Mu-Yu** [MQinghe/MiDSS#6]
Hello, for your very large contribution to the article, can you share the model weight file corresponding to the results of the article

**Comment by MQinghe** [comment]
Sorry, we were using a temporary server for the experiment and did not save the model locally. Apologies again.

**Comment by Xi-Mu-Yu** [comment]
> 很抱歉，我们使用了临时服务器进行实验，没有在本地保存模型。再次道歉。

Oh, that's really a pity, but I still have a problem, that is, I used Fundus data to train the first domain and get a model weight, but when I used this model weight to test, I found that this model weight got the results in the script on the test files of four domains, but the results were so many that I was very puzzled, and the picture below is the result of my test.

![%GTZ)CV2`%FZ7TINZNOESVR](https://github.com/user-attachments/assets/46cfad8e-2ed4-4efb-80cb-28f7026b6f7d)

**Comment by MQinghe** [comment]
Thank you for your interest in our work! Lines 3 to 18 show the test performance of the model across four different domains. Lines 20 to 22 provide the average performance across these four domains. We used four metrics to present the performance: Dice, Jaccard, 95HD, and ASD. CUP and DISC refer to the two segmentation targets in the fundus dataset.

**Comment by Xi-Mu-Yu** [comment]
> 感谢您对我们工作的关注！第 3 行到第 18 行显示了模型在四个不同领域的测试性能。第 20 行到第 22 行提供了这四个域的平均性能。我们使用了四个指标来表示性能：Dice、Jaccard、95HD 和 ASD。CUP 和 DISC 是指 fundus 数据集中的两个分割目标。

Wow, I am very confused about the results of the Fundus dataset in the following paper, can you explain to me how these results are calculated? I understand it this way, as shown in the figure of the fundus dataset result graph of the article: use 20 images of each domain as labeled data, and then get weights through training with other unlabeled data in this domain, and then test in four domains, which gets the training results of the first domain, and so on, there should be a total of 4 domains of data, how to deal with these 4 sets of data? I don't know if I understand this part correctly.

![B`DTY6}C{)JUXLGNHKMKN1H](https://github.com/user-attachments/assets/3083e141-ffe8-4b71-9506-4d39a75aa592)

**Comment by MQinghe** [comment]
We use the mean of the four experimental sets as the final result, as indicated in the blue box.

**Comment by Xi-Mu-Yu** [comment]
> We use the mean of the four experimental sets as the final result, as indicated in the blue box.

Then take 20 images in a domain for testing each time, train 4 domains separately to get the 4 best weights, and then test the 4 weights to get the average value of each weight in the 4 domains, and take the model with the highest average value as the best model to get the results of each of the 4 domains. I wonder if my understanding is correct?

**Comment by MQinghe** [comment]
I think there might be some misunderstanding. For a segmentation method, represented by a row in the table, we conduct four independent experiments. In the i-th experiment, we use 20 labeled samples from domain i and unlabeled samples from other domains. The weights obtained from this training are then averaged across the four domains, which represent the result for domain i in the corresponding column.

**Comment by Xi-Mu-Yu** [comment]
> 我认为可能会有一些误解。对于由表中一行表示的分割方法，我们执行了四个独立的实验。在第 i 个实验中，我们使用来自结构域 i 的 20 个标记样本和来自其他结构域的未标记样本。然后，从此训练中获得的权重在四个域中平均，这四个域表示相应列中域 i 的结果。

Oh, and that's to take the following four lines of code to get the 4 weight models, and then test them separately to average them.

python train.py --dataset fundus --lb_domain 1 --lb_num 20 --save_name domain1 --gpu 0
python train.py --dataset fundus --lb_domain 2 --lb_num 20 --save_name domain2 --gpu 0
python train.py --dataset fundus --lb_domain 3 --lb_num 20 --save_name domain3 --gpu 0
python train.py --dataset fundus --lb_domain 4 --lb_num 20 --save_name domain4 --gpu 0

**Comment by MQinghe** [comment]
That's right

**Comment by Xi-Mu-Yu** [comment]
> 没错

Thank you very much for your patience in answering my questions, I will do my best to promote and quote this work, and finally thank you and your team for your contribution to the semi-supervised learning area, thank you very much.
